// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAgLELKfS6-QyOa9o6R7AlwzasVm6yTM2w',
    appId: '1:1013376702973:web:630cabfb2eb89a50a3e194',
    messagingSenderId: '1013376702973',
    projectId: 'dip-app-c7e68',
    authDomain: 'dip-app-c7e68.firebaseapp.com',
    storageBucket: 'dip-app-c7e68.appspot.com',
    measurementId: 'G-GC77ZMZ8BC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOlJwd3RCHkhlbaO443sdOkWiYROmgCw8',
    appId: '1:1013376702973:android:1fe2ae074e2efc9fa3e194',
    messagingSenderId: '1013376702973',
    projectId: 'dip-app-c7e68',
    storageBucket: 'dip-app-c7e68.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjxkP_OLymE8HmUUkq9a-nCH8NAOU1uRo',
    appId: '1:1013376702973:ios:343c6d04410af4e8a3e194',
    messagingSenderId: '1013376702973',
    projectId: 'dip-app-c7e68',
    storageBucket: 'dip-app-c7e68.appspot.com',
    iosBundleId: 'com.ntu.dipApp2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBjxkP_OLymE8HmUUkq9a-nCH8NAOU1uRo',
    appId: '1:1013376702973:ios:343c6d04410af4e8a3e194',
    messagingSenderId: '1013376702973',
    projectId: 'dip-app-c7e68',
    storageBucket: 'dip-app-c7e68.appspot.com',
    iosBundleId: 'com.ntu.dipApp2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAgLELKfS6-QyOa9o6R7AlwzasVm6yTM2w',
    appId: '1:1013376702973:web:7c942afd5e51d0d2a3e194',
    messagingSenderId: '1013376702973',
    projectId: 'dip-app-c7e68',
    authDomain: 'dip-app-c7e68.firebaseapp.com',
    storageBucket: 'dip-app-c7e68.appspot.com',
    measurementId: 'G-M5CF2GV830',
  );
}
