// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOlJwd3RCHkhlbaO443sdOkWiYROmgCw8',
    appId: '1:1013376702973:android:1fe2ae074e2efc9fa3e194',
    messagingSenderId: '1013376702973',
    projectId: 'dip-app-c7e68',
    databaseURL: 'https://dip-app-c7e68-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'dip-app-c7e68.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjxkP_OLymE8HmUUkq9a-nCH8NAOU1uRo',
    appId: '1:1013376702973:ios:343c6d04410af4e8a3e194',
    messagingSenderId: '1013376702973',
    projectId: 'dip-app-c7e68',
    databaseURL: 'https://dip-app-c7e68-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'dip-app-c7e68.appspot.com',
    iosBundleId: 'com.example.dipApp2',
  );

}